### ISSUE TITLE
Initialising the npm container is broken using Meteor version 1.3

### ISSUE THREAD

**Issue by oliverlloyd** [highcharts/highcharts-meteor#1]
Using this package with latest version of Meteor causes errors. v1.3 of Meteor includes a new integration with NPM.

```
$ meteor create hc-test
$ cd hc-test/
$ meteor update
This project is already at Meteor 1.3, the latest release.
$ meteor add highcharts:highcharts-meteor
highcharts:highcharts-meteor  added, version 0.2.1
highcharts:highcharts-meteor: Official wrapper for Highcharts, Highstock and Highmaps charting libraries.
$ meteor
[[[[[ ~/Code/hc-test ]]]]]

=> Started proxy.
=> Started MongoDB.
Highcharts initialized, please restart Meteor.
$ meteor
[[[[[ ~/Code/hc-test ]]]]]

=> Started proxy.
=> Started MongoDB.
highcharts-container: updating npm dependencies -- highcharts...

/Users/oliver/.meteor/packages/meteor-tool/.1.3.0_3.10nvw69++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: Builder can not write without either data or a file path or a symlink path: web.browser/packages/highcharts-container/client/config.highcharts.json
    at Builder.write (/tools/isobuild/builder.js:251:13)
    at Builder.writeToGeneratedFilename (/tools/isobuild/builder.js:382:10)
    at /tools/isobuild/isopack.js:1400:27
    at Array.forEach (native)...
```

**Comment by pawelfus** [comment]
Thank you for reporting. Have you tried to install Highcharts directly from [NPM](https://www.npmjs.com/package/highcharts)? Using `package.json` and `dependencies` ?

**Comment by oliverlloyd** [comment]
Yes, that works fine and going forward might be the better option but I thought I'd raise this here anyway.

**Comment by oliverlloyd** [comment]
For the thread, using highcharts in Meteor 1.3 via NPM:

From the cmd line:
`$ meteor npm install  --save highcharts`

Then, at the top of each file where you want to use the `Highcharts` object:
`import Highcharts from 'highcharts';`

The [official guide](http://guide.meteor.com/using-packages.html#using-npm) gives more information on this subject.

**Comment by oliverlloyd** [comment]
Coming back to this. Using basic Highcharts with npm was pretty simple but I'm struggling to have any luck with HighStock. I'm using:

`import Highcharts from 'highcharts/highstock';`

But when I try to render a highstock chart I get:
```
Uncaught TypeError: a.setAttribute is not a function
W  @ modules.js?hash=f4cac86…:147
Ca.getContainer @ modules.js?hash=f4cac86…:357
Ca.firstRender  @ modules.js?hash=f4cac86…:371
Ca.init @ modules.js?hash=f4cac86…:349
(anonymous function)  @ modules.js?hash=f4cac86…:537
a.(anonymous function)  @ modules.js?hash=f4cac86…:159
(anonymous function)  @ modules.js?hash=f4cac86…:553
a.(anonymous function)  @ modules.js?hash=f4cac86…:159
Ca.getArgs  @ modules.js?hash=f4cac86…:348
z.Chart @ modules.js?hash=f4cac86…:348
z.StockChart.z.stockChart @ modules.js?hash=f4cac86…:557
render  @ trax_reports.js:899
render  @ explore.js:194
```
or
```
Uncaught TypeError: B[(intermediate value)(intermediate value)(intermediate value)] is not a constructor
E.jQuery.fn.highcharts	@	modules.js?hash=a1e60a6…:622
render	@	trax_reports.js:898
render	@	explore.js:194
```
Depending on how I try to render the chart.

**Comment by 06chaynes** [comment]
@oliverlloyd I tried your suggestion but upon loading the page I receive the following error in the console:
Uncaught SyntaxError: Unexpected token import

Highcharts remains undefined.

**Comment by oliverlloyd** [comment]
Are you using `Meteor 1.3.1`? (Just checking!)

If so, maybe you have don't the import statements at the top of the file? They have to be right at the top before anything else.

**Comment by 06chaynes** [comment]
I am using 1.3.1. I also tried 1.3.2.1 for good measure. Both end for me with the same result.

**Comment by oliverlloyd** [comment]
`1.3.2` is out? That was fast!

Not really sure why you're getting this to be honest. But it sounds like more of a general issue rather than a HighCharts specific one. A couple of thoughts though:
1. Did you definitely remove the old `highcharts:highcharts-meteor` atmosphere package?
2. As a test, are you able to `meteor npm install --save moment` and then `import moment from 'moment;`?

**Comment by 06chaynes** [comment]
I did for sure remove the old package and when I tested using moment I got the same error.

**Comment by oliverlloyd** [comment]
Ah, then it's more of a general meteor issue. You could try `forums.meteor.com`, you should find someone over there that can help. They'll probably want some example code though.

That said, the error you're getting sounds a lot like the browser isn't able to parse the file. Hmm, are you using Blaze and putting the `import thing from 'thing'` line at the top of a js file or are you using React?

**Comment by 06chaynes** [comment]
I am using Blaze yes, I made sure I put the import at the very top of the JS file, right above my "use strict"; statement. I also removed that and tried just to be sure. I will check out the forums thanks.

**Comment by Tallyb** [comment]
Did not work for me either on 1.3.1 . Highcharts is not imported neither via the package, nor via npm and import.

**Comment by oliverlloyd** [comment]
@Tallyb the previous poster had a problem with the `import` keyword in his project, not Highcharts specifically. Highcharts via Npm should work fine.

This package (`highcharts-meteor`) most definitely won't work in 1.3. For 1.3.1 you're best of going with Npm. If there are issues, try `meteor npm install moment --save` as a test to see if you have  more generic issue.

**Comment by pawelfus** [comment]
Closing this ticket. To use Highcharts in Meteor 1.3+ use npm package. Added description to [atmosphere package](https://atmospherejs.com/highcharts/highcharts-meteor).
