### ISSUE TITLE
Error with config.highcharts.json

### ISSUE THREAD

**Issue by Laboratory** [highcharts/highcharts-meteor#3]
Hello,

How can I resolve this problem?

``` sh
Error: Builder can not write without either data or a file path or a symlink path: web.browser/packages/highcharts-container/client/config.highcharts.json
```

Thx, V

**Comment by pawelfus** [comment]
Hi @Laboratory ,

Which version of Meteor do you have?

Thanks,
Paweł

**Comment by Laboratory** [comment]
Hey, @pawelfus Meteor 1.3.4.4

**Comment by pawelfus** [comment]
Please, follow the instructions from [readme](https://atmospherejs.com/highcharts/highcharts-meteor):

> This package will not work with Meteor 1.3+.
> 
> To use Highcharts in Meteor 1.3+, install package from npm:
> 
> `meteor npm install --save highcharts`
> Now, include Highcharts in your project:
> 
> `var Highcharts = require(‘highcharts');`
> More details you can find in the official [documentation](http://www.highcharts.com/docs/getting-started/install-from-npm).
